### ISSUE TITLE
Resizing elements where transform origin is top-left

### ISSUE THREAD

**Issue by truunk** [andyzee/jquery-resizable-rotation-patch#1]
Thank you for the work you have done, it works really well in the main but i have just come up with an issue when the transform origin is top left instead of center.

I am happy to try and fix this and submit a pull request but i need a little bit of guidance into where i would look to update the code to deal with this?  Any ideas?

**Comment by andyzee** [comment]
Hello, @truunk, actually it's not maintained anymore, so you'll have to find the right place yourself :)
You can also try https://github.com/unlocomqx/jQuery-ui-resizable-rotation-patch based on this patch.
